console.log("------------jQuery------------");
// jQuery is a JavaScript library that simplifies the process of writing JavaScript code.

$(document).ready(function () {
    // jQuery methods go here...
    let allElements = $("*");
    console.log(allElements);

    let elementById = $("#mainTitle");
    console.log(elementById);

    let elementsByClass = $(".innerWrapper");
    console.log(elementsByClass);

    let firstWrapper = elementsByClass.first();
    console.log(firstWrapper);

    let lastWrapper = elementsByClass.last();
    console.log(lastWrapper);

    let paragraphsByTag = $("p");
    console.log(paragraphsByTag);

    let firstParagraph = $("p:first");
    console.log(firstParagraph);

    let lastParagraph = $("p:last");
    console.log(lastParagraph);

    let secondParagraph = $("#second :nth-child(2)");
    console.log(secondParagraph);

    let firstChild = $(".innerWrapper :first-child");
    console.log(firstChild);

    let lastChild = $(".innerWrapper :last-child");
    console.log(lastChild);

    console.log(lastChild.text()); // same as innerText

    let inputValue = $("#input1").val();
    console.log(inputValue);

    let changedValue = $("#input1").val("Changed value");
    console.log(changedValue);

    $("#emptyDiv").html("<p>I am paragraph generated by jQuery</p>"); // same as innerHTML
    console.log($("#emptyDiv").html());

    let emptyDiv = document.getElementById("emptyDiv");
    console.log(emptyDiv.innerHTML); // cannot mix jQuery and JavaScript

    $("h1").before("<p>Code injected with .before</p>");
    $("h1").after("<p>Code injected with .after</p>");

    paragraphsByTag.first().css("color", "blue");
    paragraphsByTag.last().css(
        {
            "color": "red",
            "background-color": "lightblue",
            "font-weight": "bold",
        } // multiple CSS properties are defined in an object
    );

    paragraphsByTag.first().hide(); // same as display: none

    // jQuery event listeners
    let button = $("#btn");

    // button.on("click", function () {
    //     console.log("Button clicked");
    // }); // Way 1

    button.click(function () {
        console.log("Button clicked");
    }); // Way 2
});